[versions]
fabric-api = "0.140.2+1.21.11"
fabric-kotlin = "1.13.8+kotlin.2.3.0"
fabric-loader = "0.17.2"
fabric-loom = "1.14-SNAPSHOT"
kotlin = "2.3.0"
mccfishingmessages = "1.21.11"
minecraft = "1.21.11"
modmenu = "11.0.3"
noxesium = "3.0.0"
slf4j = "2.0.16"
yacl = "3.8.1+1.21.11-fabric"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
mccfishingmessages = { module = "maven.modrinth:mcc-fishing-messages-mod", version.ref="mccfishingmessages" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
noxesium = { module = "com.noxcrew.noxesium:fabric", version.ref = "noxesium"}
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }

[bundles]

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
